# Generated by Django 3.0.3 on 2020-03-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('profile', models.ImageField(upload_to='pics')),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.TextField()),
                ('basePrice', models.IntegerField()),
                ('currentPrice', models.IntegerField()),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
    ]
