# Generated by Django 3.0.3 on 2020-03-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200315_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
