# Generated by Django 3.0.3 on 2020-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
