# Generated by Django 3.0.3 on 2020-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_bidder',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
