# Generated by Django 3.0.3 on 2020-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img2',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='img3',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='img4',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
