# Generated by Django 3.0.3 on 2020-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200316_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
