# Generated by Django 3.0.3 on 2020-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200316_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='start_time',
        ),
    ]
