# Generated by Django 3.0.3 on 2020-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_item_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidderid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
