# Generated by Django 3.0.3 on 2020-03-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20200317_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bidderid',
        ),
    ]
