# Generated by Django 3.0.3 on 2020-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_remove_item_bidderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bidder',
            field=models.IntegerField(null=True),
        ),
    ]
