# Generated by Django 3.0.3 on 2020-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_ownermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.CharField(max_length=10),
        ),
    ]
