# Generated by Django 3.0.3 on 2020-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20200320_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.CharField(default='unsold', max_length=10),
        ),
    ]
