# Generated by Django 3.0.3 on 2020-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20200320_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sendwinmail',
            field=models.CharField(default='unsended', max_length=7),
        ),
    ]
